
const prompt = require('prompt-sync')();

//const prenome = prompt('What is your last name? ');
//const age = prompt('What is your age? ');
//const gender = prompt('What is your gender? ');
//const email = prompt('What is your email? ');
//console.log(`ton informations sont: name: ${name}! ;last name: ${prenome}!;age: ${age}; gender: ${gender};email: ${email}.`);



//let C = parseFloat (prompt("enter the temperature"));
//let K = C + 273.15 ;
//console.log (K);


//let distanceenkm = parseFloat(prompt("enter la distance en km "))
//let distancenyard = distanceenkm * 1093.61 ;
//console.log (distancenyard);


//let vitesseenkmparh = prompt("enter la vitesse en km/H")
//let vitesseenmpars  = vitesseenkmparh *  0.27778 ;
//console.log ( vitesseenmpars);


//let c = Number(prompt("Enter temperature in Celsius"));
//if (c < 0) {
    //console.log("L'eau est solide");
//} else if (c >= 0 && c <= 100) {
    //console.log("L'eau est liquide");
//} else {
    //console.log("L'eau est un gaz");



//   CHALLENGE 6   let a =parseFloat (prompt("enter a"));
//let b = parseFloat (prompt("enter b"));
//console.log(` la somme: ${a+b}! ;:multiplication:  ${a*b}!;division: ${a/b}; difference: ${a-b}.`);


 // let a = Number(prompt("entre la premier distance"));
   // let b = Number(prompt("entre la deuxieme distance"));
     // let c = Number(prompt("entre la troisieme distance"));
      //console .log((a*b*c) **(1/3));


 // CHALLENGE 9 FUH ERROR   let x1 = Number(prompt("entre  x lwl"));   
   // let y1 = Number(prompt("entre y lwl "));  
     //let z1 = Number(prompt("z lwl "));
       //let x2 = Number(prompt("entre la x tani"));
     //let y2 = Number(prompt("entre y tani"));
     //let z2 = Number(prompt("entre z tani"));
//console .log( Math0.sqrt ((x2-x1)**2 + (y2-y1)**2 + (z2-z1)**2))


/*let number = Number(prompt('entre a number : '))
let a = number % 10
let b = parseInt(number / 10)%10
let c = parseInt(number / 100) % 10
let d = parseInt(number /1000)

console.log(a,b,c,d); 
*/

function happybirthday (name , age) {
    console .log("happy birthday ");
     console .log(`happy birthday ${name}`);
      console .log(`happy birthday your age is ${age}`);
 }
  happybirthday("abdelaziz ", 19);